import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { useEffect, useState } from 'react'
import { Button, Flex, Heading, Input, Spinner, Text, Toast, useToast } from '@chakra-ui/react'
import Contract from '../../backend/artifacts/contracts/Bank.sol/Bank'
import { ethers } from 'ethers'
import Events from '@/components/Events/Events'
import Bank from '@/components/Bank/Bank'

export default function Home() {

  return (
    <>
      <Head>
        <title>Bank App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Bank />
    </>
  )
}
