import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'


export default function Home() {

  const [number, setNumber] = useState(0)

  useEffect(() => {
    console.log("Page is ready")
  }, [])

  useEffect(() => {
    console.log("Number is updated")
  }, [number])

  useEffect(() => {
    console.log("Rerendering happened, something changed in the application")
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {number}
        <button onClick={() => setNumber(number + 1)}>Increment</button>
        <button onClick={() => setNumber(number - 1)}>Decrement</button>
      </div>
    </>
  )
}
